name: v2ray
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_v2ray: ^1.0.8
  dio: ^5.4.2+1
  dartz: ^0.10.1
  device_apps: ^2.2.0
  gradient_borders: ^1.0.1
  shared_preferences: ^2.2.3
  country_flags: ^2.2.0
  badges: ^3.1.2
  get_it: ^7.6.4
  get: ^4.6.6
  bloc: ^8.1.4
  lottie: ^2.7.0
  top_snackbar_flutter: ^3.1.0
  connectivity_plus: ^4.0.0
  dart_ipify: ^1.1.1
  flutter_bloc: ^8.1.5
  device_information: ^0.0.4
  url_launcher: ^6.2.3
  permission_handler: ^11.0.0

  equatable: ^2.0.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: PTH
      fonts:
        - asset: fonts/peyda-Thin.ttf
          weight: 100

    - family: PR
      fonts:
        - asset: fonts/peyda-Regular.ttf
          weight: 200

    - family: PM
      fonts:
        - asset: fonts/peyda-Medium.ttf
          weight: 300

    - family: PL
      fonts:
        - asset: fonts/peyda-light.ttf
          weight: 400

    - family: PB
      fonts:
        - asset: fonts/peyda-Black.ttf
          weight: 500

    - family: PXL
      fonts:
        - asset: fonts/peyda-extralight.ttf
          weight: 600

    - family: PXB
      fonts:
        - asset: fonts/peyda-ExtraBold.ttf
          weight: 800

    - family: PBOLD
      fonts:
        - asset: fonts/peyda-Bold.ttf
          weight: 900
